### PR TITLE
[EMX] Define Aureo stackup for EMX

### PR DESCRIPTION
**Pull request by tryuan99**
This PR defines the Aureo stackup for EMX simulations and adds scripts to load EMX into Virtuoso.
* `aureo.proc` defines the Aureo stackup.  Since conductors are not allowed to be adjacent to each other, the conductor layers are 1 nm shorter than their actual height, and vias are defined to connect adjacent layers.
* Sample square inductor test structures were laid out using SOI1, POLY1, and HIGHMETAL1 with outer diameters of 200 um, 300 um, 400 um, and 500 um.  The trace width was kept constant at 10 um, and probe pads are adjacent to the inductor leads.  In the future, defining a pcell for these inductors would be useful.

To run EMX on Aureo, ensure that `EMX_HOME` is defined in the `setup.sh` script and run `source .bashrc` again.

inductors

### CODE REVIEW

**Comment by daniellovell** [comment]
image
Needs to fail gracefully if EMX_HOME not specified, give the user some warning, but not throw error

**Review by daniellovell — CHANGES_REQUESTED** [review]
(see screenshot in thread) needs graceful handling of no EMX_HOME

**Comment by tryuan99** [comment]
Added a check for the `EMX_HOME` environment variable and a warning message if it does not exist:
warning

**Review by daniellovell — APPROVED** [review]

**Comment by daniellovell** [comment]
LGTM 👍

**Pull request merged**
